### PR TITLE
Add X as optional arg to call signature of MCAcqusitionObjective

### PR DESCRIPTION
**Pull request by Balandat**
Summary: This was requested in https://github.com/pytorch/botorch/issues/663.

Differential Revision: D25938012

### CODE REVIEW

**Comment by Balandat** [comment]
@jduerholt do the changes in this PR work for you?

**Comment by jduerholt** [comment]
Hi @Balandat,

this looks exactly like what I need. I will test it over the course of the week. The intention of my issue from Friday was not that you should implement it on the weekend ... 

Thank you very much!

Best,

Johannes

**Comment by Balandat** [comment]
@jduerholt any updates? FWIW I'm planning to cut a new release soon, if this works for you I'll include this PR.

**Comment by jduerholt** [comment]
Hi @Balandat,

sorry for not responding yet. I was so busy with other things that I could not find the time to test it so far. But my plan is to have a basic implementation and test in our workflow until the end of the week. Hope this works for you.

Best,

Johannes

**Comment by jduerholt** [comment]
Hi @Balandat

I see you are very active here. I tested the feature today in a single objective setup (no qehvi). Works like a charm! Multiobjective will be tested next week, but I do not expect any problems. So from my side it could and should be included in the next release ;-)

Have a nice weekend and many thanks!

Best,

Johannes

**Comment by Balandat** [comment]
Great, thanks for the feedback. Will merge this in shortly.

**Pull request closed without merging**
