### PR TITLE
[Codemod] Use time.monotonic instead of time.time to measure duration

### PR DESCRIPTION
**Pull request by Balandat**
Following best practices to avoid results being affected by system clock changes.

### CODE REVIEW

**Review by saitcakmak — APPROVED** [review]
Lgtm

**Comment by Balandat** [comment]
Hmm interesting looks like this is failing on windows. Seems unlikely that this is caused by this change though? Running a test suite on main to verify.

**Comment by Balandat** [comment]
Confirmed that conda windows failure is unrelated: https://github.com/pytorch/botorch/actions/runs/2879093795. Landing.

**Comment by saitcakmak** [comment]
It is a bit weird that it suddenly started failing only on windows and only when using conda. Only if the error message way a little bit informative...

**Comment by Balandat** [comment]
Yeah, presumably some conda package update was broken - let's just see if it goes away by itself, if it doesn't by early next week we can investigate further.

**Pull request closed without merging**
