### PR TITLE
Hack around missing pytorch 1.13.1 binaries for py3.11 on mac

### PR DESCRIPTION
**Pull request by Balandat**
This fix is needed to avoid errors in the CI

### CODE REVIEW

**Comment by saitcakmak** [comment]
I think you need to do this for the deploy_on_release workflow as well: https://github.com/pytorch/botorch/blob/main/.github/workflows/deploy_on_release.yml

**Comment by Balandat** [comment]
I don't think so, we don't pin to the specific torch version there, so it should just install 2.0.1 for that one

**Comment by saitcakmak** [comment]
Yeah, that makes more sense :D

**Review by saitcakmak — APPROVED** [review]

**Comment by Balandat** [comment]
Pushing the changes to https://github.com/pytorch/botorch/tree/no_mac_py311_ci to test it in the workflows. For some reason it's not picking up the new min_torch_version assignment - not sure what's going on I'll try a few things.

**Comment by Balandat** [comment]
Updated, newest version tested here: https://github.com/pytorch/botorch/actions/runs/5733147831

**Pull request closed without merging**
