### PR TITLE
Modify qNEHVI to support DeterministicModels

### LINKED ISSUE #966: [Bug] Error while using NEHVI with deterministic models
# 🐛 Bug

The `_set_sampler()` method of `qNEHVI` throws an `IndexError` when used with a `DeterministicModel` due to `model.base_sample_shape` returning `torch.Size()`. Prior to #829,  `model.base_sample_shape` would return `model.event_shape` and the code would run without any issues.

## To reproduce

** Code snippet to reproduce **
```python
import torch
from botorch.acquisition.multi_objective.monte_carlo import qNoisyExpectedHypervolumeImprovement
from botorch.models.deterministic import GenericDeterministicModel
from botorch.sampling import IIDNormalSampler

ref_point = torch.tensor([-1, -2])
train_X = torch.rand(10, 2)
det_model = GenericDeterministicModel(lambda X: X)

acqf = qNoisyExpectedHypervolumeImprovement(
    model=det_model,
    ref_point=ref_point,
    X_baseline=train_X,
    sampler=IIDNormalSampler(1),
)
posterior = acqf.model.posterior(train_X)
q = train_X.shape[-2]
print(f"Event shape: {posterior.event_shape}, base sample shape: {posterior.base_sample_shape}")
acqf._set_sampler(q=q, posterior=posterior)
```

** Stack trace/error message **
```
Traceback (most recent call last):
  File "/Users/saitcakmak/PycharmProjects/robust_mobo/debug/nehvi_deterministic_posterior_bug.py", line 19, in <module>
    acqf._set_sampler(q=q, posterior=posterior)
  File "/opt/anaconda3/envs/robust_mobo/lib/python3.9/site-packages/botorch/acquisition/multi_objective/monte_carlo.py", line 672, in _set_sampler
    end_idx = current_base_samples.shape[-2]
IndexError: tuple index out of range
Event shape: torch.Size([10, 2]), base sample shape: torch.Size([])
```

## Expected Behavior

Should run without errors. The base sample shape needs to be the same as the event shape for the NEHVI methods to work properly.

## System information

**Please complete the following information:**
BoTorch: Current main branch.

## Additional Context

The code to reproduce is a stripped out version of the code for running NEHVI with RFFs. This error currently prevents running NEHVI with RFFs on the main branch.

cc @sdaulton, @Balandat

### PR DESCRIPTION
**Pull request by saitcakmak**
## Motivation

Fixes #966 by disabling `_cache_root` and `_set_sampler` when using a deterministic model with qNEHVI.

### Have you read the [Contributing Guidelines on pull requests](https://github.com/pytorch/botorch/blob/main/CONTRIBUTING.md#pull-requests)?

Yes

## Test Plan

Unit tests.

## Related PRs

(If this PR adds or changes functionality, please take some time to update the docs at https://github.com/pytorch/botorch, and link to your PR here.)
#896 - I will update that once I figure out a good way to support set valued objectives as discussed offline.
cc @sdaulton

### CODE REVIEW

**Review by Balandat — APPROVED** [review]
Thanks for the fix. Have you ever tried using qNEHVI with `ModelList` and `PosteriorList`? There you can combine both probabilistic and deterministic models, handling that properly will probably require some other fixes. But we can get this PR in!

**Comment by saitcakmak** [comment]
I haven't had a use-case for mixing models yet. So far, it has been either GP or RFF. Maybe we could make an example for the paper where one of the objectives is deterministic? Could be interesting. Agreed on the implementation side, you'd probably need to make non-trivial changes to both `_cache_root` and `_set_sampler`.

**Comment by Balandat** [comment]
Yeah combining GP and deterministic models has come up in cost-aware optimization, where the cost is some known function of the parameters. In that case you could of course also just model that based on data you generate, but why bother fitting a model if you know the ground truth already....

**Comment by saitcakmak** [comment]
This was merged in as part of #1037.

**Pull request closed without merging**
