### PR TITLE
require PyTorch 1.2

### PR DESCRIPTION
**Pull request by sdaulton**
Summary: require pytorch 1.2 to incorporate changes regarding bool tensors

Reviewed By: Balandat

Differential Revision: D16725568

### CODE REVIEW

**Comment by Tenoke** [comment]
I'm running into multiple issues today, and I guess this is the cause. I didn't record all of them, but e.g. with qNEI I often get

```
/usr/local/lib/python3.6/dist-packages/gpytorch/utils/eig.py in batch_symeig(mat)
     21 
     22     for i in range(batch_shape.numel()):
---> 23         evals, evecs = mat[i].symeig(eigenvectors=True)
     24         mask = evals.ge(0)
     25         eigenvectors[i] = evecs * mask.type_as(evecs).unsqueeze(0)

RuntimeError: symeig_cpu: the algorithm failed to converge; 2 off-diagonal elements of an intermediate tridiagonal form did not converge to zero.
```

Also setting q=1 no longer works for qEI, possibly a few other things, too.

**Comment by Balandat** [comment]
@Tenoke is this on gpytorch/botorch master or with a recent release? Master should work fine on pytorch 1.2, but there likely are issues with with gpytorch / botorch on the 0.3.4 / 0.1.2 releases due to the breaking changes in pytorch. The changes here won't affect conda/pip install, but since the requirement is pytorch>=1.1 , gpytorch/botorch installed from pip/conda will likely run into issues. I'll prepare a new release for pytorch 1.2 compatibility. 

cc @jacobrgardner, @gpleiss

**Comment by Tenoke** [comment]
I run into them using master via pip.
```
pip install git+https://github.com/cornellius-gp/gpytorch.git
pip install git+https://github.com/pytorch/botorch.git
```

**Comment by sdaulton** [comment]
> Also setting q=1 no longer works for qEI

What is the failure you are seeing here?

**Comment by Tenoke** [comment]
```
/usr/local/lib/python3.6/dist-packages/gpytorch/utils/lanczos.py in lanczos_tridiag(matmul_closure, max_iter, dtype, device, matrix_shape, batch_shape, init_vecs, num_init_vecs, tol)
     80     # Copy over alpha_0 and beta_0 to t_mat
     81     t_mat[0, 0].copy_(alpha_0)
---> 82     t_mat[0, 1].copy_(beta_0)
     83     t_mat[1, 0].copy_(beta_0)
     84 

IndexError: index 1 is out of bounds for dimension 1 with size 1
```

**Comment by Balandat** [comment]
Hmm I wonder if this is caused by one of the recent gpytorch commits (e.g. https://github.com/cornellius-gp/gpytorch/commit/f51232a858df98139897ed031647967fda1eac97) - we haven't thoroughly tested against these yet. Let me pull them in and see.

**Comment by Balandat** [comment]
@Tenoke do you have code for reproing this? I just tested this on the latest botorch/gpytorch masters with pytorch 1.2 and qNEI with q=1 seems to work fine. What model are you using?

**Comment by Tenoke** [comment]
@Balandat The last error is about **qEI** with q=1, as @sdaulton asked about the **qEI** error specifically. It happens every time with every model.

The qNEI one doesn't happen consistently, and can happen with any q. I can try to create a reproducible example for that one, but it will likely have to wait until Monday.

**Comment by Balandat** [comment]
Reproable example would be good. FWIW, the following code runs fine:

```
import torch

from botorch.models import SingleTaskGP
from gpytorch.mlls import ExactMarginalLogLikelihood
from botorch.fit import fit_gpytorch_model
from botorch.test_functions import neg_hartmann6
from botorch.acquisition import qExpectedImprovement


train_X = torch.rand(200, 6)  # use a bigger model to use lanczos
train_Y = neg_hartmann6(train_X)
train_Y += 0.1 * torch.rand_like(train_Y)

model = SingleTaskGP(train_X, train_Y)
mll = ExactMarginalLogLikelihood(model.likelihood, model)
fit_gpytorch_model(mll);

qEI = qExpectedImprovement(model, best_f=0.0)

test_X = torch.rand(1, 6)
qEI(test_X)\

test_X = torch.rand(2, 1, 6)
qEI(test_X)
```

If you're doing vanilla EI w/o an objective transform, you can use `ExpectedImprovement` (the `AnalyticAquisitionFunction`) instead - that should be faster anyway.

**Comment by Tenoke** [comment]
[Here](https://colab.research.google.com/drive/1jdG80buyudBXgy7eHZ8f-rp3WOjKsnd5)'s an example in colab.

**Comment by Balandat** [comment]
@Tenoke, I just verified that your nb runs fine on both pytorch 1.1 and 1.2 under the most recent gpytorch/botorch masters. 

The issue seems to be the following in your install log: 
> `Requirement already satisfied (use --upgrade to upgrade): gpytorch==0.3.4 from git+https://github.com/cornellius-gp/gpytorch.git in /usr/local/lib/python3.6/dist-packages`


So it looks like you're running the gpytorch 0.3.4. release, which doesn't work well with the breaking changes in pytorch 1.2 (these have been fixed on gpytorch master).

**Comment by Tenoke** [comment]
Thanks - I hadn't noticed.

For what is worth, I still run into 

```
/usr/local/lib/python3.6/dist-packages/gpytorch/utils/eig.py in batch_symeig(mat)
     21 
     22     for i in range(batch_shape.numel()):
---> 23         evals, evecs = mat[i].symeig(eigenvectors=True)
     24         mask = evals.ge(0)
     25         eigenvectors[i] = evecs * mask.type_as(evecs).unsqueeze(0)

RuntimeError: symeig_cpu: the algorithm failed to converge; 2 off-diagonal elements of an intermediate tridiagonal form did not converge to zero.
```

Wheras I didnt before Thursday. I'll try to isolate it today.

**Comment by Tenoke** [comment]
@Balandat I've made a reproducible example for the symeig_cpu issue [here](https://colab.research.google.com/drive/17cwdAwYWTTI-fv0mZ_d4NFsejb5JZxIP). Anecdotally, this was not happening before Thursday.

Should I post a separate issue for it?

**Comment by Balandat** [comment]
Thanks @Tenoke, and yes, please open a separate issue so we can keep things somewhat compartmentalized.

**Pull request closed without merging**
